version: "3.8"
services:
  db:
    image: mysql:8.0  # 使用 MySQL 8.0 镜像
    container_name: bili  # 容器名称
    ports:
      - "3306:3306"  # 将容器的 3306 端口映射到主机的 3306 端口
    environment:
      MYSQL_ROOT_PASSWORD: Li114514  # 设置 root 用户的密码
      MYSQL_DATABASE: bili  # 创建默认数据库
      MYSQL_USER: bili_user  # 创建普通用户
      MYSQL_PASSWORD: Li114514  # 设置普通用户的密码
    volumes:
      - mysql_data:/var/lib/mysql  # 持久化 MySQL 数据
    networks:
      - bili_network  # 将 MySQL 容器加入网络

  web:
    build: .  # 使用当前目录的 Dockerfile 构建后端服务
    container_name: bili_backend  # 容器名称
    ports:
      - "5001:5001"  # 将容器的 5000 端口映射到主机的 5000 端口
    depends_on:
      - db  # 依赖 MySQL 容器
    environment:
      DB_HOST: db  # MySQL 容器的主机名
      DB_USER: bili_user  # MySQL 用户名
      DB_PASSWORD: Li114514  # MySQL 密码
      DB_NAME: bili  # MySQL 数据库名
    networks:
      - bilibili_network  # 将后端服务加入网络

volumes:
  mysql_data:  # 定义 MySQL 数据卷

networks:
  bilibili_network:  # 定义网络